[package]
name = "BeariumSession"
version = "1.0.0"
authors = []

[addresses]
bearium_session = "_"

[dev-addresses]
bearium_session = "0xda"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"
